Dockerfile + updated lifecycle how to test
vire/kyberia-client pull request #4
Opened 2016-11-11 21:20 UTC by vire

* added pushstate-server to serve compiled app

2016-11-12 11:37 UTC, rlaucik commented on Dockerfile
> +ARG REACT_APP_BACKEND_URL # env variable to specify API URL durin build
had to remove comment from this line to make it work (otherwise I've got an error: "ARG requires exactly one argument definition")

2016-11-12 12:07 UTC, vire commented on Dockerfile
> +ARG REACT_APP_BACKEND_URL # env variable to specify API URL durin build
Thanks for the hint! I've added the comment to tell why I'm passing a variable `REACT_APP_BACKEND_URL` during build time...

2016-11-12 12:55 UTC, devopsmariocom requested changes

2016-11-12 12:55 UTC, elmariofredo commented on Dockerfile
> +    mv node_modules /app/node_modules &&\
why not run yarn directly inside of `/app` folder?

2016-11-12 12:55 UTC, elmariofredo commented on Dockerfile
> +COPY . /app
why not copy app in step when you are copying package.json?

2016-11-12 12:57 UTC, vire commented on Dockerfile
> +    mv node_modules /app/node_modules &&\
This RUN will be cached so if I don't change `package.json` docker will use this layer from cache regardless of src code changes `/app`

2016-11-12 13:03 UTC, vire commented on Dockerfile
> +    mv node_modules /app/node_modules &&\
I think you're right could be simplified maybe in one step, I can try it out

2016-11-14 05:30 UTC, elmariofredo commented on Dockerfile
> +    mv node_modules /app/node_modules &&\
yep not sure why they came up with intermediate tmp folder, maybe it didn't work before ¯\_(ツ)_/¯

2016-11-14 05:35 UTC, elmariofredo commented on Dockerfile
> +COPY . /app
I'm not sure about your exact use case but your are right with catching but as it's only local catching I don't see it as much valuable but YMMV.

Also any reason to not use yarn.lock file to ensure exact packages versions?

2016-11-14 08:57 UTC, vire commented on Dockerfile
> +COPY . /app
I wasn't sure about putting yarn.lock right there until 1.0 of yarn, but ths comment conviced me!

2016-11-14 16:41 UTC, rlaucik approved these changes

2016-11-14 16:59 UTC, merged